export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT:"REMOVE_SELECTED_PRODUCT",
    CART_PRODUCT: "CART_PRODUCT",
    REMOVE_PRODUCT_CART: "REMOVE_PRODUCT_CART",
    UPDATE_CART_COUNT: "UPDATE_CART_COUNT",
}
